---
version: '3.7'

services:
  rconfig_db:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_USER: rconfig
    networks:
      - rconfig_net_db
  rconfig:
    build:
      context: .
    image: rconfig:0.0.1
    networks:
      - rconfig_net_db
    depends_on:
      - rconfig_db

networks:
  rconfig_net_db:
    internal: true
    name: rconfig_net_db
...
